import{CHUNK_LIBRARY}from'./chunks';
import{definitionEndPose,sampleDefinition}from'./path';
import{pickWeighted,random01}from'./prng';
import type{ChunkDefinition,ChunkFamilyId,ChunkInstance,GlobalPose,RenderChunkInstance,WorldSnapshot}from'./types';
export interface WorldStreamerOptions{seed:string;minLive?:number;maxLive?:number;rebaseThreshold?:number}
export class WorldStreamer{readonly seed:string;readonly minLive:number;readonly maxLive:number;readonly rebaseThreshold:number;private chunks:ChunkInstance[]=[];private history:ChunkFamilyId[]=[];private pool:number[]=[];private nextPoolId=0;private generatedCount=0;private originGlobal={x:0,z:0};private originEpoch=0;private rebases=0;
constructor(opts:WorldStreamerOptions){this.seed=opts.seed;this.minLive=opts.minLive??5;this.maxLive=opts.maxLive??7;this.rebaseThreshold=opts.rebaseThreshold??520;while(this.chunks.length<this.minLive)this.appendChunk();}
private chooseDefinition(sequenceIndex:number):ChunkDefinition{const recent=this.history.slice(-3);let eligible=CHUNK_LIBRARY.filter(c=>!recent.slice(-1).includes(c.family));if(sequenceIndex<2)eligible=eligible.filter(c=>c.family==='residential-ribbon'||c.family==='tea-stop'||c.family==='town-high-street');if(!eligible.length)eligible=CHUNK_LIBRARY;return pickWeighted(eligible,c=>{let w=c.weight;if(recent.includes(c.family))w*=.18;const prev=recent.at(-1);if(prev==='market-junction'&&c.family==='town-high-street')w*=.45;if(prev==='paddy-open'&&c.family==='bridge-green')w*=1.55;if(prev==='bridge-green'&&c.family==='paddy-open')w*=1.35;return w;},random01(this.seed,'world-sequence',sequenceIndex));}
private appendChunk(){const sequenceIndex=this.generatedCount,definition=this.chooseDefinition(sequenceIndex),previous=this.chunks.at(-1),startPose:GlobalPose=previous?previous.endPose:{x:0,z:0,heading:0},startDistance=previous?previous.endDistance:0,endPose=definitionEndPose(definition,startPose),poolId=this.pool.pop()??this.nextPoolId++;this.chunks.push({poolId,sequenceIndex,definition,startDistance,endDistance:startDistance+definition.length,startPose,endPose});this.history.push(definition.family);this.generatedCount++;if(this.history.length>8)this.history.shift();}
private trimBehind(d:number){while(this.chunks.length>this.minLive&&this.chunks[1]&&this.chunks[1].endDistance<d-115){const removed=this.chunks.shift()!;this.pool.push(removed.poolId);}}
private ensureAhead(d:number){while((this.chunks.at(-1)?.endDistance??0)<d+330){if(this.chunks.length>=this.maxLive){const removed=this.chunks.shift()!;this.pool.push(removed.poolId);}this.appendChunk();}while(this.chunks.length<this.minLive)this.appendChunk();}
private findChunk(d:number){return this.chunks.find(c=>d>=c.startDistance&&d<=c.endDistance)??this.chunks.at(-1)!;}
sampleGlobal(d:number):GlobalPose{const c=this.findChunk(d);return sampleDefinition(c.definition,d-c.startDistance,c.startPose);}
update(logicalDistance:number):WorldSnapshot{this.trimBehind(logicalDistance);this.ensureAhead(logicalDistance);let playerGlobal=this.sampleGlobal(logicalDistance);if(Math.hypot(playerGlobal.x-this.originGlobal.x,playerGlobal.z-this.originGlobal.z)>this.rebaseThreshold){this.originGlobal={x:playerGlobal.x,z:playerGlobal.z};this.originEpoch++;this.rebases++;}playerGlobal=this.sampleGlobal(logicalDistance);const chunks:RenderChunkInstance[]=this.chunks.map(c=>({...c,renderX:c.startPose.x-this.originGlobal.x,renderZ:c.startPose.z-this.originGlobal.z}));return{seed:this.seed,logicalDistance,playerGlobal,playerRender:{...playerGlobal,x:playerGlobal.x-this.originGlobal.x,z:playerGlobal.z-this.originGlobal.z},originGlobal:{...this.originGlobal},originEpoch:this.originEpoch,rebases:this.rebases,chunks,activeCount:this.chunks.length,pooledCount:this.pool.length,generatedCount:this.generatedCount};}
getGeneratedCount(){return this.generatedCount;}
getActiveChunks(){return this.chunks.slice();}
}